FROM openjdk:17 AS build

COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN ./mvnw dependency:resolve

COPY src src
RUN ./mvnw package

FROM openjdk:17
WORKDIR account
COPY --from=build targe/*.jar account.jar
ENTRYPOINT ["Java", "-jar","account.jar"]
